version: "3.8"
services:
  digitalocean-dynamic-dns:
    container_name: digitalocean-dynamic-dns
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
networks:
  default:
    driver: bridge
    enable_ipv6: true
